CREATE DATABASE gowit;

USE gowit;

CREATE TABLE users (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	profile_picture_url VARCHAR(512) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE films (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT DEFAULT NULL,
	release_year YEAR DEFAULT NULL,
	popularity INT UNSIGNED DEFAULT 0,
	poster_image_url VARCHAR(512) DEFAULT NULL,
	trailer_url VARCHAR(512) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorites (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	notes TEXT DEFAULT NULL,
	user_id BIGINT UNSIGNED NOT NULL,
	film_id BIGINT UNSIGNED NOT NULL,

	CONSTRAINT fkey_favorites_user
		FOREIGN KEY (user_id)
		REFERENCES users(id)
		ON DELETE CASCADE,

	CONSTRAINT fkey_favorites_film
		FOREIGN KEY (film_id)
		REFERENCES films(id)
		ON DELETE CASCADE,

	UNIQUE KEY unique_user_film (user_id, film_id)
);
